### ISSUE TITLE
Using size of defintions for sorting

### ISSUE THREAD

**Issue by masatake** [universal-ctags/citre#103]
```
#ifdef CONFIG_PROC_FS
static inline void crypto_init_proc(void)
{ }
#else
...
```
```
void __init crypto_init_proc(void)
{
	proc_create_seq("crypto", 0, NULL, &crypto_seq_ops);
}
```

I expect the latter one is listed before the former one in xref buffer.
The size of the definition calculated from `$end - $line` can be used as hints.
This is applicable to functions and methods.

**Comment by AmaiKinono** [comment]
I get the idea. I think I can find time to work on this in several days.

**Comment by masatake** [comment]
Works fine. Thank you.
