### ISSUE TITLE
`project-current` returns `(vc Git "~/.emacs.d/")` for a git repo

### ISSUE THREAD

**Issue by condy0919** [universal-ctags/citre#113]
```elisp
(defun citre--project-root ()
  "Full path of project root of current buffer.
This uses `project-current' internally."
  (when-let ((project (project-current nil)))
    (expand-file-name (cdr project))))
```

So `expand-file-name` throws an exception when passing `'(Git "~/.emacs.d")` to it.

https://github.com/emacs-mirror/emacs/commit/86969f9658e278ebacb3d625d0309046ff1f2b54 caused it.

**Comment by AmaiKinono** [comment]
Thanks for the report. My PC is currently broken (sad...) so please wait a few days before I fix this.
