### ISSUE TITLE
citre--up-directory does not return parent directory on Linux

### ISSUE THREAD

**Issue by zbelial** [universal-ctags/citre#117]
I'm not familiar with `rx`, but it seems that the regexp returned by rx in `citre--up-directory` will always match an UNIX absolute path, and this leads to `citre-tags-file-path` does not work correctly in some case.

**Comment by zbelial** [comment]
FYI. This bug was introduced in a recent commit d17511e.

**Comment by AmaiKinono** [comment]
Thanks. I've seen the problem. It's a serious mistake. I should have written test for it.
