### ISSUE TITLE
Error Message While Opening File

### ISSUE THREAD

**Issue by drcxd** [universal-ctags/citre#118]
I am using emacs 29.0.50 and when I try to open a file in a git repository, i.e. in a directory tree which contains .git at the project's root, citre will pump an error message:
```
citre--project-root: Wrong type argument: stringp, (Git "/path/to/project/root")
```
The file buffer is created, but it is not automatically switched to be active as usual.

**Comment by AmaiKinono** [comment]
It should have been fixed in https://github.com/universal-ctags/citre/commit/b84428d282533069718ba10aa237df54024d5ca1, could you try with the latest version?

**Comment by drcxd** [comment]
Yes, you are right. I do not know why I cannot pull the latest package from melpa. I just downloaded the package from melpa within a weeks and it was built in January. Maybe network issue. I have to download melpa archives and install packages from local. Is this (citre issue rather than network issue) an emacs-29 exclusive? I have another version 28 instance and it works just fine.

**Comment by AmaiKinono** [comment]
> Is this (citre issue rather than network issue) an emacs-29 exclusive?

Yes.
