### ISSUE TITLE
passing new options to universal-ctags through citre-create-tags-file

### ISSUE THREAD

**Issue by Pierre-Andre** [universal-ctags/citre#119]
when using citre-create-tags-file we are taken to a command editing buffer and the line
```--languages=C,C++ ;; programming languages to be scanned```
leads to change in the following way
```
--languages=EmacsLisp,Org ;; programming languages to be scanned
--exclude=*.*
--exclude-exception=*.org
```

but it has to be
```
--languages=EmacsLisp,Org
--exclude=*.*
--exclude-exception=*.org
```
without the comment (otherwise adding options in the next two lines does not work…)

**Comment by AmaiKinono** [comment]
Thanks, it's a problem introduced in https://github.com/universal-ctags/citre/commit/a3e58aad69ffd43a7511f34c1606d1d27772bb57.

In the help message I wrote:

```
- Lines start with ;; are ignored
```

But `;;` actually doesn't start a comment at the middle of a line. Now the command template is rearranged as

```
;; programming languages to be scanned
--languages=C,C++
```

so it should work now.
