### ISSUE TITLE
java support

### ISSUE THREAD

**Issue by e665107** [universal-ctags/citre#122]
Does it support java very well?

**Comment by masatake** [comment]
Oh, sorry. This is the issue for citre. I assumed this is an issue for ctags itself.

**Comment by e665107** [comment]
i want to use emacs + tags to see android aosp source code, instead of android ide. But I can't find a good solution!

**Comment by e665107** [comment]
Hey  I have solved this problem by using gtags

**Comment by AmaiKinono** [comment]
Great. I'll close the issue then.
