### ISSUE TITLE
"global stderr" process left for every open file

### ISSUE THREAD

**Issue by railwaycat** [universal-ctags/citre#137]
Hi, thank you for the recent release! 

After upgraded to the recent release, I started to notice a weird behavior: It looks like citre will left a "global stderr" process for every open file and they won't be cleanup automatically, no matter `citre-mode` is on or off for that buffer. 

My reproduce steps:

0. I start with an empty Emacs config file.
1. `git clone` citre repo to `~/.emacs.d/citre"
2. All my configuration is below:
```
(add-to-list 'load-path "~/.emacs.d/citre")
(require 'citre)
(require 'citre-config)
```
3. open several regular files.
4. Exit emacs, emacs will prompt `Active processes exist; kill them and exit anyway? (yes or no)`. If I use `(list-processes)` , I can see a list of "global stderr" processes:
```
global stderr   --      open     *global-stderr*          --           Main         (serial port ?)
global stderr<… --      open     *global-stderr*-603055   --           Main         (serial port ?)
global stderr<… --      open     *global-stderr*-910393   --           Main         (serial port ?)
global stderr<… --      open     *global-stderr*-998676   --           Main         (serial port ?)
global stderr<… --      open     *global-stderr*-347810   --           Main         (serial port ?)
```
5. I didn't enable `citre-mode` on any of the buffers.

I'm using the Emacs 28.2 release, and verified above on both Linux (latest Arch Linux) and macOS (12.6). This behavior not shows up on `emacs -q` with no config.

Since for this configuration, the only thing enabled is citre, I would like to see if you have any info of this behavior?

**Comment by AmaiKinono** [comment]
Thanks for the report.

Should be fixed, please test.

**Comment by railwaycat** [comment]
Thank you! I no longer see this issue after upgrade to the latest.
