### ISSUE TITLE
citre-imenu-create-index-function: always discard first tag returned by citre-get-tags-buffer 

### ISSUE THREAD

**Issue by my2817** [universal-ctags/citre#154]
it's my misunderstand of some case, or a typo?
https://github.com/universal-ctags/citre/blob/4626ada80fabea6b62935567acc1cb8dad607016/citre.el#L523-L526

**Comment by AmaiKinono** [comment]
It's now fixed.

I guess the `citre-get-tags-in-buffer` call was once `citre-get-backend-and-tags-in-buffer` so it needs the `cdr`.
