### ISSUE TITLE
可以帮忙更新一下 lsp-bridge 的 citre 后端吗？

### ISSUE THREAD

**Issue by manateelazycat** [universal-ctags/citre#157]
大佬， 很多 lsp-bridge 用户都喜欢 citre， 能帮忙更新一下 lsp-bridge 的 citre 后端吗？

https://github.com/manateelazycat/lsp-bridge/blob/238b5b67ac44cb96e73efa84366b2992744fbb32/acm/acm-backend-citre.el#L1

上面是社区开发者提交的 citre 后端， 但是不支持最新版 citre, 大佬能帮忙看看吗？

谢谢

**Comment by AmaiKinono** [comment]
I tried lsp-bridge with citre backend and hasn't encounter any problem. This shows it working in c code with citre backend:

![image](https://github.com/universal-ctags/citre/assets/28714352/ba5a09f3-8ffa-4f9c-86b1-55445f467d9f)

I haven't done a thorough test, though. What's the problem with the current citre backend?

**Comment by manateelazycat** [comment]
社区已经支持最新citre版本，打扰了
