### ISSUE TITLE
peed window display issue when display-line-numbers-mode turn on

### ISSUE THREAD

**Issue by brianjcj** [universal-ctags/citre#161]
peed window display problem when display-line-numbers-mode turn on, in both gui and tui 

gui:
![图片](https://github.com/universal-ctags/citre/assets/140656/16cffe04-f23b-407e-a65a-d6996893624a)

in terminal:
![图片](https://github.com/universal-ctags/citre/assets/140656/95e5dc28-ad36-4cf8-b2b7-3f3bc5b22846)

**Comment by jsntn** [comment]
Encountered the same issue once I enabled the line numbers as shown below,

```lisp
(global-display-line-numbers-mode 1)
```

**Comment by AmaiKinono** [comment]
It's now fixed. See the [user manual](https://github.com/universal-ctags/citre/blob/master/docs/user-manual/use-citre-peek.md#fix-the-peek-window-appearance-when-displaying-line-numbers):

> If you have line numbers turned on, and is using a graphic display, then the peek window may look strange. In this situation, set `citre-peek-fill-fringe` to nil, and `citre-peek-use-dashes-as-horizontal-border` to t. Read their docstrings for details.
