### ISSUE TITLE
exclude dirs/files listed in .gitignore when create tag file

### ISSUE THREAD

**Issue by t6ui** [universal-ctags/citre#170]
I've come to understand that I can exclude directories when generating tag files using the command `ctags --exclude=@/workspace/open/linux/linux-2.6.24/.gitignore -R`. 
Is there a way to automate or customize this feature within the citre package？

**Comment by masatake** [comment]
ctags doesn't know the syntax of .gitignore. Because your ".gitignore" is not too complicated, ctags works as your expectation. See https://github.com/universal-ctags/ctags/issues/218.

**Comment by t6ui** [comment]
@masatake Ok, thank you!
