### ISSUE TITLE
Related works for transferring this repo to the u-ctags organization

### ISSUE THREAD

**Issue by AmaiKinono** [universal-ctags/citre#58]
@masatake suggests transfer this repo to the universal-ctags organization ([here](https://github.com/AmaiKinono/citre/pull/28#issuecomment-722623362)). Since Citre is now close to the 0.1 release, I'd like to do this before we get it into MELPA.

What I'd like to ask is: In the future, I may put donation links (for myself) in README. Is this acceptable for a project under the universal-ctags organization? No problem if it's not suitable, I'm still happy to transfer.

Here's what I need to do (in order):

- [x] transfer the repo
- [x] fix the links pointing to this repo in the code
- [x] finish the TODOs for v0.1 (now the only remaining task is adding more test cases)
- [x] publish to MELPA
- [x] add instructions for installing from MELPA
- [x] make a v0.1 tag
- [x] add a test for u-ctags to run tests of Citre (see below)

**Comment by masatake** [comment]
> What I'd like to ask is: In the future, I may put donation links (for myself) in README. Is this acceptable for a project under the universal-ctags organization? No problem if it's not suitable, I'm still happy to transfer.

Of course, it is o.k. However, I don't know how to do that and I myself will not receive the donation. So you must set up all you need in the u-ctags organization, as a member of the organization.

I have one optional TODO item: adding a test case to run citre's test to u-ctags repo.
So when u-ctags introduces a new change, we can confirm the change doesn't break the behavior of u-ctags that citre expects.

**Comment by AmaiKinono** [comment]
> Of course, it is o.k.

Thank you ;)

> However, I don't know how to do that and I myself will not receive the donation.

I don't know clearly too. It's just something I may want to do in the future.

You may know that mobile payment through QR code is popular in China, so one way is to simple put my QR code in the README.

> So you must set up all you need in the u-ctags organization, as a member of the organization.

I don't quite understand this statement.

> I have one optional TODO item: adding a test case to run citre's test to u-ctags repo.

OK, I can do this.

**Comment by masatake** [comment]
> You may know that mobile payment through QR code is popular in China, so one way is to simple put my QR code in the README.

Good and simple way!



>>    So you must set up all you need in the u-ctags organization, as a member of the organization.

>I don't quite understand this statement.

Please, forget the statement. I assumed that you will use the sponsor facility that Git Hub provides.

**Comment by AmaiKinono** [comment]
Just a note:

> So when u-ctags introduces a new change, we can confirm the change doesn't break the behavior of u-ctags that citre expects.

If we automatically update the tags files in Citre's unit tests, then:

- a change in u-ctags may cause the tags file being changed.
- since the tags file is different, the functions being tested may return something different, i.e., the expected output is different.
- Citre's tests will fail and they need to be manually fixed. That's extra amount of work and is out of the scope for general u-ctags developer.

So I think "Citre's tests in the u-ctags repo" should be only used to detect if changes in readtags break th

**Comment by AmaiKinono** [comment]
@masatake I'm going through the process. I need to pick a team to have access to the Citre repo. Do you suggest I put it in the `ctags-developers` team or create a new one?

**Comment by masatake** [comment]
I don't know well about the github's team mechanism well. But I think making a new team is better because it is your team!
Please, add me the team:-)

**Comment by AmaiKinono** [comment]
I've done that. Now the problem is I found I can't edit the repo description ("about"). I want to remove the "work in progress" part.

Can you make me the "owner" of the repo (I don't know if there's such thing) or can you do it for me?

**Comment by masatake** [comment]
> Can you make me the "owner" of the repo (I don't know if there's such thing) or can you do it for me?

Sure, I will try.

**Comment by masatake** [comment]
I have just made you an administrator (ADMIN).
Could you try updating "about" again?

**Comment by AmaiKinono** [comment]
> Could you try updating "about" again?

Thanks. It works now (though I have no idea what you've done :D)

**Comment by masatake** [comment]
> Thanks. It works now (though I have no idea what you've done :D)

I opened "Settings" at the top of repository's page. This action leads us a "Settings" page.
Then I chose "Manage access" in the "Settings" page.
Finally I choose "Admin" as your role.

I guess this can be done only Admin of u-ctags ORGANIZATION, not REPOSITORY.
When you find a new person as a developer of citre, and want to add the one to the member of this repo, I will assign you as an Admi of u-ctags ORGANIZATION. Is this o.k.?

If you have a trouble for setting up CI/CD environments because of your "access right", let me know.

----

I forgot saying "Welcome!".

When I started working on fishman ctags, I would like to have a real client utilizing tags file, not TAGS file.
But, soon, I found no time to do so because there are so many interesting topics in u-ctags itself.
I believed someone will develop the one if I can make ctags an *attractive* tool.
What is an attractive tool? It is explained in https://github.com/universal-ctags/citre/blob/master/docs/developer-manual/design-principle.md .

**Comment by AmaiKinono** [comment]
> When you find a new person as a developer of citre, and want to add the one to the member of this repo, I will assign you as an Admin of u-ctags ORGANIZATION. Is this o.k.?

It's OK.

> If you have a trouble for setting up CI/CD environments because of your "access right", let me know.

I just have 2 pushes and the CI works great.

> I forgot saying "Welcome!"...

Thanks! And, thanks for the attractive tool you've created ;)

**Comment by masatake** [comment]
How do you think putting the .md documents in the source tree to citre.ctags.io and make a link from ctags.io to the document?
(Though I don't understand the detail of what I have to do for booting citre.ctags.io.)

If you are interested in, could you login https://readthedocs.org ?
You can use your github account "AmaiKinono" for login.

I already made https://readthedocs.org/projects/citre/, a project page.
I guess I can invite you as a maintainer for the project if you login once.

**Comment by AmaiKinono** [comment]
I've logged in once.

My only question is if I do this, can I let Read the Docs use the docs in Citre repo directly? Seems they have an "import project" feature so this should be doable.

**Comment by masatake** [comment]
> I've logged in once.

I added "AmaiKinono" as a maintainer of   https://readthedocs.org/projects/citre/. However, I'm not sure what I did is correct or not.

> My only question is if I do this, can I let Read the Docs use the docs in Citre repo directly? Seems they have an "import project" feature so this should be doable.

Yes, please as you want. If I have to do something, let me know.

**Comment by AmaiKinono** [comment]
Sorry but I want to give up Read the Docs.

The problem is Mkdocs (a builder supported by RTD) thinks all your docs lives in a `docs_dir`. The default value of it is `docs`. So this happens:

```
WARNING  -  A relative path to '../README.md' is included in the 'nav' configuration, which is
            not found in the documentation files
WARNING  -  Documentation file 'user-manual/customization.md' contains a link to
            '../README.md' which is not found in the documentation files.
```

Yes. It strongly assumes all docs lives in `docs_dir` and refuses to find a file outside it, even if we give it the relative path.

We can try setting `docs_dir` to project root in `mkdocs.yml`:

```
docs_dir: .
```

No. It doesn't work:

```
ERROR    -  Config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent directory
            of the config file. Use a child directory instead so that the 'docs_dir' is a
            sibling of the config file.
```

There are actually a [plugin](https://github.com/oprypin/mkdocs-same-dir) that works around this problem, but you can't use it directly on Read the Docs. You have to install it, by writing a `requirements.txt` in your source tree... at this point I'm just exhausting.

I also looked into Sphinx, which actually supports markdown, but it requires a `conf.py` file. Had a look into it, it's complex... Don't want to learn it.
