### ISSUE TITLE
Tips when work with projectile

### ISSUE THREAD

**Issue by kaiwk** [universal-ctags/citre#63]
For some reason, projectile will try to load the entire TAGS every time when one open a file, see [here](https://github.com/bbatsov/projectile/blob/e8a3f11df57583ad089a4f00d652c80566ffeb09/projectile.el#L5435).

Since Citre don't need load the entire TAGS, user of projectile may need remove that hook function from `find-file-hooks` or modify it.

**Comment by AmaiKinono** [comment]
Thanks for the tip!

I'm not familiar with projectile, so I have some questions first.

> projectile will try to load the entire TAGS every time when one open a file

When we mention TAGS file, we are talking about one created by `etags` or `$ ctags -e`. This format is not supported by Citre.

The default output format of `ctags` is "tags format". The name of the tags file is also "tags".

My question is: do you use the word "TAGS" in the above sense?

Load the TAGS file into a buffer is the normal way that Emacs uses it, so I think projectile does it right. Only if it loads the tags file (*not TAGS file*) into a buffer, then it's a problem.

**Comment by AmaiKinono** [comment]
Ah, I think I understand it.

Windows thinks `TAGS` and `tags` are the same file name, so even if you created `tags` file, projectile tries to load it as `TAGS` file.

**Comment by beyondpie** [comment]
I use MacOS, and this still happens. When I use .ctags,  there is no such a problem any more. Thanks!

**Comment by AmaiKinono** [comment]
@beyondpie Thanks for the report! I looked it up and seems macOS file names are also case-insensitive. I'll write it in the docs.

**Comment by jueqingsizhe66** [comment]
`(remove-hook 'find-file-hook #'projectile-find-file-hook-function)`

it works, thanks.

**Comment by kaiwk** [comment]
> `(remove-hook 'find-file-hook #'projectile-find-file-hook-function)`

Note that this may case projectile misfunction, I'd rather redifine `projectile-find-file-hook-function` or using [el-patch](https://github.com/raxod502/el-patch).

**Comment by AmaiKinono** [comment]
The recommended way is to simply use `.tags` as the tags file name.

**Comment by AmaiKinono** [comment]
Thanks everyone for joining in!

Now we have a note for this in the [README](https://github.com/universal-ctags/citre#create-tags-file), so I'll close this.

When I finish the tags creating/updating tool, I'd like to make `.tags` the default file name so users on all platforms should be happy.
