### ISSUE TITLE
citre-tags-file-alist is invaild

### ISSUE THREAD

**Issue by TanCheamy** [universal-ctags/citre#65]
https://github.com/universal-ctags/citre/blob/ed26e100d58811b5e6f4bffd3f3490fd5725e9f8/citre-util.el#L182-L205

``` emacs-lisp
(let ((current-file (or (buffer-file-name) default-directory)) 
           (project (funcall citre-project-root-function))) 

(null "111")
nil
(null ())
t
(null '(a))
nil
;; null function is empty object t else nil

(null project)
nil
(when (and (or (not (file-name-absolute-p (car pair))) 
                         (not (file-name-absolute-p (cdr pair)))) 
                     (null project))
nil

(file-in-directory-p dir file)
;; current-file  is file
;; citre-tags-file-alist is dict
;; what if (car pair) ?
;; then (cdr pair)
(when (file-in-directory-p current-file 
                                     (expand-file-name (car pair) project)) 
nil
(cl-return (setq citre--tags-file
                            (expand-file-name (cdr pair) project)))))
```

**Comment by AmaiKinono** [comment]
I don't understand this. Please, state it clearly, or just say what's the problem you encountered.

**Comment by TanCheamy** [comment]
我想重新定义读取tags的文件路径到 project-root/.cache/.tags
我已经尝试以下赋值：
```emacs-lisp
(setq citre-tags-file-alist '((".tags" . ".cache/.ctags")))
```
设置无效后我研究了代码
我认为citre-tags-file-alist无效的

**Comment by AmaiKinono** [comment]
Translate:

I want to put my tags to `project-root/.cache/.tags`. What I did was:

```
(setq citre-tags-file-alist '((".tags" . ".cache/.ctags"))
```

and it didn't work.

---

解答：

你这种情况只要在 `citre-tags-files` 中加入 `.cache/.tags`。例如：

``` elisp
(setq citre-tags-files '("tags" ".tags" ".cache/.tags"))
```

你对 `citre-tags-file-alist` 的理解有点问题，请仔细读一下 docstring。这个变量一般用不到。

---

answer:

You need to put `.cache/.tags` into `citre-tags-files`, like:

``` elisp
(setq citre-tags-files '("tags" ".tags" ".cache/.tags"))
```

You misunderstood `citre-tags-file-alist`, please read its docstring. One doesn't need this variable for common use cases.

**Comment by TanCheamy** [comment]
OK
