### ISSUE TITLE
citre-peek-restore when calling citre-peek on a whitespace character

### ISSUE THREAD

**Issue by railwaycat** [universal-ctags/citre#73]
Currently when calling citre-peek on a white space character, it throws an error: "Wrong type argument: stringp, nil".

I would like to see if it's a good idea to bring citre-peek-restore out in this case?

**Comment by AmaiKinono** [comment]
I don't think so. We shouldn't guess the user's intention for a not well-defined operation.

But hey it's Emacs! You can do whatever you want

``` Elisp
(require 'thingatpt)

(defun citre-peek+ ()
  (interactive)
  (if (thing-at-point 'symbol)
      (citre-peek)
    (citre-peek-restore)))
```

**Comment by railwaycat** [comment]
Thanks! That is exactly what I want.
