### ISSUE TITLE
add citre-mode-map, so user can define key to override global keybindings

### ISSUE THREAD

**Issue by jiacai2050** [universal-ctags/citre#81]
```elisp
  (defvar my/citre-mode-map
    (let ((map (make-sparse-keymap)))
      (define-key map (kbd "M-.") 'citre-jump)
      (define-key map (kbd "M-,") 'citre-jump-back)
      map))
  (require 'citre)
  (require 'citre-config)
  (add-to-list 'minor-mode-map-alist (cons 'citre-mode my/citre-mode-map))
```
Currently, I hack  `minor-mode-map-alist` to do this, it would be great if this package provide it out of box.

**Comment by AmaiKinono** [comment]
If you think this is necessary, I can give `citre-mode` a map, but I think I wouldn't put any keybinding in it. You'll have to customize it yourself.

The point is, `citre-mode` is for capf/xref/imenu integration, and `citre-peek/jump` is separate from `citre-mode`. You don't have to enable `citre-mode` to use them. So conceptually they shouldn't appear in `citre-mode-map`.

If all you want is "If there's a tags file, use `citre-jump`, otherwise use xref", you can try `citre-jump+` command in the [wiki](https://github.com/universal-ctags/citre/wiki/Useful-commands).

So, what's your choice?

**Comment by jiacai2050** [comment]
Hi，I try `citre-jump+`, it works fine, but have one issue for jump elisp functions, it will prompt symbols of all elisp functions instead of go to definition of current symbol, do you have any ideas to fix this?
![image](https://user-images.githubusercontent.com/3848910/128625927-53ecf737-fc15-43cd-a8be-a9b8e0c708f5.png)

**Comment by AmaiKinono** [comment]
This didn't happen to me. Does it happen in vanilla Emacs? I suspect your configuration causes this problem.

**Comment by jiacai2050** [comment]
I can reproduce this with `emacs -Q`, which emacs version are you using? mine is 

- GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2021-03-28

**Comment by AmaiKinono** [comment]
Ah, yes, you are right.

Try this:

```elisp
(call-interactively #'xref-find-definitions)|xref-push-marker-stack
```

`|` is the cursor. Call `eval-last-sexp` (`C-x C-e`) here, and it behaves like you described. But directly type `M-x xref-find-definitions` on the symbol doesn't.

I think it has something to do with the "interactive spec", but I've never managed to understand it. Do you have any idea?

**Comment by jiacai2050** [comment]
```elisp
(defun citre-jump+ ()
    (interactive)
    (condition-case _
        (citre-jump)
      (error (let* ((xref-prompt-for-identifier nil))
               (call-interactively #'xref-find-definitions)))))
```
After dig into this, I find when xref-prompt-for-identifier is nil, prompt will be gone. Although root cause is still unclear, but it works.

I think about this issue again, it makes no harm to provide a (empty) keymap, and users can customize what they like. 
Please think again whether provide it or not.

**Comment by AmaiKinono** [comment]
> I find when xref-prompt-for-identifier is nil, prompt will be gone.

Thanks! This is good enough.

> it makes no harm to provide a (empty) keymap, and users can customize what they like.

Yes. I'll do it.

**Comment by AmaiKinono** [comment]
I've put your `citre-peek+` in the wiki, and added a `citre-mode-map`.
