### ISSUE TITLE
Feature request - Jump to/Peek any tag 

### ISSUE THREAD

**Issue by slayer152** [universal-ctags/citre#85]
Hello,

Would it be possible to provide a command to jump to and peek any tag (say, using completing-read)? 

Thanks in advance.

**Comment by AmaiKinono** [comment]
It's in the plan. In the "current status" in README, I talked about new tools I'm thinking about.

For now, you can call `xref-find-definitions` where there's no symbol at point, and it will list all tags and let you choose one using `completing-read`.

**Comment by AmaiKinono** [comment]
Close this in favor of #172.
